name: merge tables
run-name: merge tables

on:
  schedule:
    - cron:  '30 0 * * *'

jobs:
  merger:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: setup python
        id: setup_python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install pip dependencies
        id: install_dependencies
        run: pip install -r requirements.txt

      - name: run script
        id: run_script
        env:
          readme: README.md
          dataframe: content/data.csv
          header: content/text.md
          index: Name
          actor: ${{ github.actor }}
          server_url: ${{ github.server_url }}
        run: python .github/workflows/scripts/merge_table.py

      - name: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto_commit
        with:
          commit_message: ${{ steps.run_script.outputs.commit_msg }}